# 2강. 조건문, 반복문

조건문과 반복문은 모든 프로그래밍 언어에서 필수로 알아야 할 내용이다. 조건 반복문을 통해 우리가 원하는 규칙을 구현할 수 있다. 

In [1]:
import numpy as np

## 2.1 조건문

In [2]:
x = 10

if x == 1:
    print("x = 1")
else:
    print("x != 1")

x != 1


In [3]:
x = 10

if x == 1:
    print("x는 1 입니다.")
elif x == 2:
    print("x는 2 입니다.")  
elif x == 3:
    print("x는 3 입니다.")       
else:
    print("x는 4 입니다.")

x는 4 입니다.


## 2.2 반복문

In [4]:
for i in range(5): # range(5) = [0,1,2,3,4] list
    print(i)

0
1
2
3
4


In [5]:
i = 0
while i < 5:
    print(i)
    i+=1 # i = i+1
    
# i    출력
# 0    0
# 1    1
# 2    2
# 3    3
# 4    4
# 5    break

0
1
2
3
4


## 2.3 예시

### 2.3.1 이차방정식의 실근의 개수

In [6]:
# a*x**2 + b*x + c = 0
# [a, b, c] 라고 표현
f = np.random.randint(10,size=(10,3))
print(f)

[[1 1 4]
 [1 8 2]
 [8 7 5]
 [0 6 3]
 [2 1 1]
 [9 3 9]
 [5 3 7]
 [0 4 4]
 [9 8 4]
 [2 4 2]]


In [7]:
for g in f:
    if g[0] == 0:
        print("이차 방정식이 아닙니다.")
    else:
        D = g[1]**2 - 4*g[0]*g[2]
        if D == 0:
            print("서로 같은 두 실근")
        elif D > 0: 
            print("서로 다른 두 실근")
        else:
            print("서로 다른 두 허근")            

서로 다른 두 허근
서로 다른 두 실근
서로 다른 두 허근
이차 방정식이 아닙니다.
서로 다른 두 허근
서로 다른 두 허근
서로 다른 두 허근
이차 방정식이 아닙니다.
서로 다른 두 허근
서로 같은 두 실근


### 2.3.2 break문

In [8]:
pending = [1,3,5,3,8,1,4,5]

In [9]:
# 짝수가 나오면 바로 종료한다.
for i in pending:
    if i % 2 == 0:
        print(i,'입니다.')
        break

8 입니다.


### 2.3.3 try-except문

In [11]:
x = [1,2,3,"s",4,5]

for i in x:
    y = i + 1
    print(y)

2
3
4
5
6


In [12]:
x = [1,2,3,"s",4,5]

for i in x:
    try:
        y = i + 1
        print(y)
    except:
        print(i, "는 오류 입니다.")

2
3
4
s 는 오류 입니다.
5
6
