In [50]:
import torch
from torch import nn
criterion  = nn.MSELoss()
prediction = torch.Tensor([0, 0])# 예측값
target     = torch.Tensor([10, 20]) # 정답
loss       = criterion(prediction, target)
print(loss)

tensor(250.)


In [51]:
criterion_reduction_none = nn.MSELoss(reduction='none')
loss = criterion_reduction_none(prediction, target)
print(loss)
# tensor([4., 1., 0., 1., 4.])


tensor([100., 400.])


In [69]:
criterion = nn.CrossEntropyLoss()
input = torch.autograd.Variable(torch.randn((2,3)))
tgt = torch.autograd.Variable(torch.LongTensor(3).random_(5))


In [70]:
input

tensor([[-0.2959,  0.3394,  0.8477],
        [-0.9463, -0.3030,  0.5096]])

In [71]:
tgt

tensor([4, 0, 2])

In [72]:

loss = criterion(input,tgt)

ValueError: Expected input batch_size (2) to match target batch_size (3).